# Generated by Django 5.1.6 on 2025-02-23 12:39

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingcomponent',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='The embedding vector for the component', null=True),
        ),
    ]
