# Generated by Django 5.1.6 on 2025-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0002_alter_buildingcomponent_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingcomponent',
            name='unit_of_measure',
            field=models.CharField(choices=[('METERS', 'Meters'), ('CENTIMETERS', 'Centimeters'), ('MILLIMETERS', 'Millimeters'), ('SQUARE_METERS', 'Square Meters'), ('CUBIC_METERS', 'Cubic Meters'), ('LITERS', 'Liters'), ('KILOGRAMS', 'Kilograms'), ('UNIT', 'Unit')], max_length=255),
        ),
    ]
