# Generated by Django 5.1.6 on 2025-03-09 19:14

import building_design_evaluations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDesignEvaluation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=building_design_evaluations.models.upload_building_design_evaluation_file)),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_design_evaluations', to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
