# Generated by Django 5.1.6 on 2025-03-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_design_evaluations', '0001_initial'),
        ('draft_building_designs', '0002_alter_designdrawingcomponentmetadata_bom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdesignevaluation',
            name='draft_building_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='draft_building_designs.draftbuildingdesign'),
        ),
    ]
