"""Django CORS settings."""

from core.constants import (
    DJANGO_CORS_ALLOW_CREDENTIALS,
    DJANGO_CORS_ALLOW_HEADERS,
    DJANGO_CORS_ALLOWED_ORIGINS,
)

__all__ = (
    "CORS_ALLOWED_ORIGINS",
    "CORS_ALLOW_CREDENTIALS",
    "CORS_ALLOW_HEADERS",
)

CORS_ALLOWED_ORIGINS = DJANGO_CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = DJANGO_CORS_ALLOW_CREDENTIALS
CORS_ALLOW_HEADERS = DJANGO_CORS_ALLOW_HEADERS
