# Generated by Django 5.1.6 on 2025-02-23 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('dimensions', models.JSONField(blank=True, help_text='The dimensions of the material', null=True)),
                ('unit_of_measure', models.CharField(choices=[('METERS', 'Meters'), ('SQUARE_METERS', 'Square Meters'), ('CUBIC_METERS', 'Cubic Meters'), ('LITERS', 'Liters'), ('KILOGRAMS', 'Kilograms'), ('UNIT', 'Unit')], max_length=255)),
                ('cost_per_unit_of_measure', models.PositiveIntegerField(help_text='Cost per unit in cents (integer)')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
