# Generated by Django 5.1.6 on 2025-03-05 23:45

import django.db.models.deletion
import draft_building_designs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_components', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDrawing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('STRUCTURAL_DRAWING', 'Structural Drawing'), ('ARQUITECTURAL_DRAWING', 'Arquitectural Drawing')], max_length=255)),
            ],
            options={
                'verbose_name': 'Design Drawing',
                'verbose_name_plural': 'Design Drawings',
            },
        ),
        migrations.CreateModel(
            name='DesignDrawingComponentMetadata',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('FOUNDATION_PLAN', 'Foundation Plan'), ('FRAMING_PLAN', 'Framing Plan')], max_length=255)),
                ('subtype', models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], max_length=255)),
                ('data', models.JSONField(null=True)),
                ('justification', models.TextField(null=True)),
                ('design_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drawing_components_metadata', to='draft_building_designs.designdrawing')),
            ],
            options={
                'verbose_name': 'Design Drawing Component Metadata',
                'verbose_name_plural': 'Design Drawing Component Metadata',
            },
        ),
        migrations.CreateModel(
            name='DesignDrawingDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('FOUNDATION_PLAN', 'Foundation Plan'), ('FRAMING_PLAN', 'Framing Plan')], max_length=255)),
                ('subtype', models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], max_length=255)),
                ('file', models.FileField(upload_to=draft_building_designs.models.upload_design_drawing_document)),
                ('design_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='draft_building_designs.designdrawing')),
            ],
            options={
                'verbose_name': 'Design Drawing Document',
                'verbose_name_plural': 'Design Drawing Documents',
            },
        ),
        migrations.CreateModel(
            name='DraftBuildingDesign',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2'), ('PHASE_3', 'Phase 3')], default='PHASE_1', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_building_designs', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignDrawingCluster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('design_drawing_components_metadata', models.ManyToManyField(related_name='clusters', to='draft_building_designs.designdrawingcomponentmetadata')),
                ('building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'verbose_name': 'Design Drawing Cluster',
                'verbose_name_plural': 'Design Drawing Clusters',
            },
        ),
        migrations.AddField(
            model_name='designdrawing',
            name='building_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign'),
        ),
        migrations.CreateModel(
            name='DraftBuildingDesignBuildingComponent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('justification', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('building_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building_components.buildingcomponent')),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='building_components',
            field=models.ManyToManyField(related_name='draft_building_designs', through='draft_building_designs.DraftBuildingDesignBuildingComponent', to='building_components.buildingcomponent'),
        ),
    ]
