# Generated by Django 5.1.6 on 2025-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
