# Generated by Django 5.1.6 on 2025-03-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='phase',
            field=models.CharField(choices=[('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2'), ('PHASE_3', 'Phase 3')], default='PHASE_1', max_length=255),
        ),
    ]
