# Generated by Django 5.1.6 on 2025-03-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingcomponentmetadata',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
