# Generated by Django 5.1.6 on 2025-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='bom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designdrawingcomponentmetadata',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
