# Generated by Django 5.1.6 on 2025-03-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0002_draftbuildingdesign_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbuildingdesign',
            name='description',
        ),
    ]
