# Generated by Django 5.1.6 on 2025-03-15 15:54

import django.db.models.deletion
import draft_building_designs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0002_draftbuildingdesign_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBuildingDesignDrawingDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=draft_building_designs.models.get_draft_building_design_drawing_document_upload_path)),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
