# Generated by Django 5.1.6 on 2025-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0002_designdrawingcomponentmetadata_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingcomponentmetadata',
            name='bom',
            field=models.JSONField(null=True),
        ),
    ]
