# Generated by Django 5.1.6 on 2025-03-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0003_remove_draftbuildingdesign_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbuildingdesign',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='draftbuildingdesign',
            name='name',
        ),
    ]
