# Generated by Django 5.1.6 on 2025-03-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0003_designdrawingcomponentmetadata_bom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designdrawingcomponentmetadata',
            options={'ordering': ['created_at'], 'verbose_name': 'Design Drawing Component Metadata', 'verbose_name_plural': 'Design Drawing Component Metadata'},
        ),
    ]
