# Generated by Django 5.1.6 on 2025-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0003_draftbuildingdesigndrawingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesigndrawingdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
