# Generated by Django 5.1.6 on 2025-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0004_draftbuildingdesigndrawingdocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesigndrawingdocument',
            name='type',
            field=models.CharField(choices=[('DETAIL', 'Detail'), ('STRUCTURE', 'Structure')], default='DETAIL', max_length=255),
        ),
    ]
