# Generated by Django 5.1.6 on 2025-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0004_remove_draftbuildingdesign_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=255),
        ),
    ]
