# Generated by Django 5.1.6 on 2025-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0004_alter_designdrawingcomponentmetadata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingcomponentmetadata',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
