# Generated by Django 5.1.6 on 2025-03-29 22:55

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("draft_building_designs", "0005_draftbuildingdesigndrawingdocument_type"),
    ]

    operations = [VectorExtension()]
