# Generated by Django 5.1.6 on 2025-03-04 23:49

import django.db.models.deletion
import draft_building_designs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0005_draftbuildingdesign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDrawingDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=draft_building_designs.models.upload_design_drawing_document)),
            ],
            options={
                'verbose_name': 'Design Drawing Document',
                'verbose_name_plural': 'Design Drawing Documents',
            },
        ),
        migrations.CreateModel(
            name='DesignDrawing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('STRUCTURAL_DRAWING', 'Structural Drawing'), ('ARQUITECTURAL_DRAWING', 'Arquitectural Drawing')], max_length=255)),
                ('building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'verbose_name': 'Design Drawing',
                'verbose_name_plural': 'Design Drawings',
            },
        ),
        migrations.CreateModel(
            name='DesignDrawingPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('FOUNDATION_PLAN', 'Foundation Plan'), ('FRAMING_PLAN', 'Framing Plan')], max_length=255)),
                ('subtype', models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], max_length=255)),
                ('plan_metadata', models.JSONField(null=True)),
                ('design_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.designdrawing')),
                ('documents', models.ManyToManyField(related_name='design_drawings', to='draft_building_designs.designdrawingdocument')),
            ],
            options={
                'verbose_name': 'Design Drawing Plan',
                'verbose_name_plural': 'Design Drawing Plans',
            },
        ),
        migrations.AddField(
            model_name='designdrawingdocument',
            name='design_drawing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.designdrawingplan'),
        ),
    ]
