# Generated by Django 5.1.6 on 2025-03-29 22:56

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0006_auto_20250329_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXFDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_data', models.TextField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('tags', models.JSONField(blank=True, help_text='Array of tags of the element in the DXF file', null=True)),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dxf_documents', to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
