# Generated by Django 5.1.6 on 2025-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0006_designdrawingdocument_designdrawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingplan',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
