# Generated by Django 5.1.6 on 2025-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0007_designdrawingplan_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
