# Generated by Django 5.1.6 on 2025-03-29 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0007_dxfdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbuildingdesign',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='draftbuildingdesign',
            name='status',
        ),
        migrations.CreateModel(
            name='DraftBuildingCalculation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('STRUCTURE_CALCULATION', 'Structure Calculation'), ('FLOOR_CALCULATION', 'Floor Calculation'), ('ROOF_CALCULATION', 'Roof Calculation'), ('WALL_CALCULATION', 'Wall Calculation')], default='STRUCTURE_CALCULATION', max_length=255)),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
