# Generated by Django 5.1.6 on 2025-03-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0008_designdrawingplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdrawingplan',
            name='design_drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drawing_plans', to='draft_building_designs.designdrawing'),
        ),
    ]
