# Generated by Django 5.1.6 on 2025-03-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0008_remove_draftbuildingdesign_phase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DraftBuildingCalculation',
            new_name='DraftBuildingDesignCalculationModule',
        ),
    ]
