# Generated by Django 5.1.6 on 2025-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0009_rename_draftbuildingcalculation_draftbuildingdesigncalculationmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesigncalculationmodule',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=255),
        ),
    ]
