# Generated by Django 5.1.6 on 2025-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0009_alter_designdrawingplan_design_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdrawingplan',
            name='name',
            field=models.CharField(default='Pormenor do muro de fundação', max_length=255),
            preserve_default=False,
        ),
    ]
