# Generated by Django 5.1.6 on 2025-03-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0010_draftbuildingdesigncalculationmodule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbuildingdesigncalculationmodule',
            name='draft_building_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_modules', to='draft_building_designs.draftbuildingdesign'),
        ),
    ]
