# Generated by Django 5.1.6 on 2025-03-30 11:36

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0011_alter_draftbuildingdesigncalculationmodule_draft_building_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxfdocument',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
