# Generated by Django 5.1.6 on 2025-03-30 11:47

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0012_alter_dxfdocument_embedding_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXFEntity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadata of the entity in the DXF file', null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('tags', models.JSONField(blank=True, help_text='Array of tags of the element in the DXF file', null=True)),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dxf_entities', to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DXFDocument',
        ),
    ]
