# Generated by Django 5.1.6 on 2025-03-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0013_dxfentity_delete_dxfdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dxfentity',
            options={'ordering': ['created_at'], 'verbose_name': 'DXF Entity', 'verbose_name_plural': 'DXF Entities'},
        ),
    ]
