# Generated by Django 5.1.6 on 2025-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0014_alter_dxfentity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbuildingdesigncalculationmodule',
            name='type',
            field=models.CharField(choices=[('STRUCTURE_PROJECT', 'Structure Project')], default='STRUCTURE_PROJECT', max_length=255),
        ),
    ]
