# Generated by Django 5.1.6 on 2025-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0015_alter_draftbuildingdesigncalculationmodule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbuildingdesign',
            name='status',
            field=models.CharField(choices=[('CREATING_FOOTING_COMPONENTS', 'Creating Footing Components'), ('CREATING_COLUMN_COMPONENTS', 'Creating Column Components'), ('CREATING_BEAM_COMPONENTS', 'Creating Beam Components'), ('CREATING_SLAB_COMPONENTS', 'Creating Slab Components'), ('CREATED', 'Created'), ('CREATED_WITH_ERRORS', 'Created With Errors')], default='CREATING_FOOTING_COMPONENTS', max_length=255),
        ),
    ]
