# Generated by Django 5.1.6 on 2025-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0016_draftbuildingdesign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbuildingdesigndrawingdocument',
            name='type',
            field=models.CharField(choices=[('FOOTING_DETAIL', 'Footing Detail'), ('COLUMN_DETAIL', 'Column Detail'), ('BEAM_DETAIL', 'Beam Detail'), ('SLAB_DETAIL', 'Slab Detail')], default='FOOTING_DETAIL', max_length=255),
        ),
    ]
