# Generated by Django 5.1.6 on 2025-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0017_alter_draftbuildingdesigndrawingdocument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbuildingdesign',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('CREATING_FOOTING_COMPONENTS', 'Creating Footing Components'), ('CREATING_COLUMN_COMPONENTS', 'Creating Column Components'), ('CREATING_BEAM_COMPONENTS', 'Creating Beam Components'), ('CREATING_SLAB_COMPONENTS', 'Creating Slab Components'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATING_FOOTING_COMPONENTS', max_length=255),
        ),
    ]
