# Generated by Django 5.1.6 on 2025-04-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0018_alter_draftbuildingdesign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbuildingdesigndrawingdocument',
            name='type',
            field=models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], default='FOOTING', max_length=255),
        ),
    ]
