# Generated by Django 5.1.6 on 2025-04-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_building_designs', '0019_alter_draftbuildingdesigndrawingdocument_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbuildingdesignbuildingcomponent',
            name='bom',
        ),
        migrations.RemoveField(
            model_name='draftbuildingdesignbuildingcomponent',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='draftbuildingdesignbuildingcomponent',
            name='task_id',
        ),
    ]
