# Generated by Django 5.1.6 on 2025-03-05 23:45

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        ("studies", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="BuildingComponent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "component_data",
                    models.JSONField(
                        blank=True, help_text="The data for the component", null=True
                    ),
                ),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="The embedding vector for the component",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WALL", "Wall"),
                            ("FLOOR", "Floor"),
                            ("CEILING", "Ceiling"),
                            ("ROOF", "Roof"),
                            ("DOOR", "Door"),
                            ("WINDOW", "Window"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[("EXTERIOR", "Exterior"), ("INTERIOR", "Interior")],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingComponentMaterial",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("METERS", "Meters"),
                            ("CENTIMETERS", "Centimeters"),
                            ("MILLIMETERS", "Millimeters"),
                            ("SQUARE_METERS", "Square Meters"),
                            ("CUBIC_METERS", "Cubic Meters"),
                            ("LITERS", "Liters"),
                            ("KILOGRAMS", "Kilograms"),
                            ("UNIT", "Unit"),
                        ],
                        max_length=255,
                    ),
                ),
                ("justification", models.TextField(default="")),
                (
                    "building_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="building_components.buildingcomponent",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="buildingcomponent",
            name="materials",
            field=models.ManyToManyField(
                related_name="building_components",
                through="building_components.BuildingComponentMaterial",
                to="materials.material",
            ),
        ),
        migrations.CreateModel(
            name="BuildingComponentSourceStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="building_components.buildingcomponent",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studies.study"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buildingcomponent",
            name="source_studies",
            field=models.ManyToManyField(
                related_name="building_components",
                through="building_components.BuildingComponentSourceStudy",
                to="studies.study",
            ),
        ),
        migrations.AddIndex(
            model_name="buildingcomponentsourcestudy",
            index=models.Index(fields=["study"], name="study_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="buildingcomponentsourcestudy",
            unique_together={("building_component", "study")},
        ),
    ]
