# Generated by Django 5.1.6 on 2025-03-15 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingComponent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('component_data', models.JSONField(blank=True, help_text='The data for the component', null=True)),
                ('type', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], max_length=255)),
                ('subtype', models.CharField(choices=[('PAD_FOOTING', 'Pad Footing'), ('STRIP_FOOTING', 'Strip Footing'), ('ISOLATED_FOOTING', 'Isolated Footing')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingComponentEvaluation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_data', models.JSONField(blank=True, help_text='The data for the evaluation', null=True)),
                ('rationale', models.TextField(blank=True, help_text='The rationale for the evaluation', null=True)),
                ('building_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_components.buildingcomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
