# Generated by Django 5.1.6 on 2025-03-09 19:13

import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="BuildingComponent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "component_data",
                    models.JSONField(
                        blank=True, help_text="The data for the component", null=True
                    ),
                ),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="The embedding vector for the component",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("FOUNDATION", "Foundation"), ("FRAMING", "Framing")],
                        max_length=255,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("FOOTING", "Footing"),
                            ("COLUMN", "Column"),
                            ("BEAM", "Beam"),
                            ("SLAB", "Slab"),
                            ("WALL", "Wall"),
                            ("FLOOR", "Floor"),
                            ("CEILING", "Ceiling"),
                            ("ROOF", "Roof"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
