# Generated by Django 5.1.6 on 2025-03-01 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0001_initial'),
        ('draft_building_designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnReinforcementMetadata',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_metadata', models.JSONField(blank=True, help_text='The metadata for the component', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image showing the foundation details', null=True, upload_to='foundation_metadata/')),
                ('building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ColumnReinforcementDetails',
        ),
    ]
