# Generated by Django 5.1.6 on 2025-03-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='buildingcomponent',
            name='subtype',
        ),
        migrations.AlterField(
            model_name='buildingcomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_components', to='building_components.buildingcomponenttype'),
        ),
    ]
