# Generated by Django 5.1.6 on 2025-02-24 01:48

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0001_initial'),
        ('materials', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingcomponent',
            name='unit_of_measure',
        ),
        migrations.AlterField(
            model_name='buildingcomponent',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='The embedding vector for the component', null=True),
        ),
        migrations.CreateModel(
            name='BuildingComponentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('METERS', 'Meters'), ('CENTIMETERS', 'Centimeters'), ('MILLIMETERS', 'Millimeters'), ('SQUARE_METERS', 'Square Meters'), ('CUBIC_METERS', 'Cubic Meters'), ('LITERS', 'Liters'), ('KILOGRAMS', 'Kilograms'), ('UNIT', 'Unit')], max_length=255)),
                ('justification', models.TextField(default='')),
                ('building_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_components.buildingcomponent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='buildingcomponent',
            name='materials',
            field=models.ManyToManyField(related_name='building_components', through='building_components.BuildingComponentMaterial', to='materials.material'),
        ),
        migrations.CreateModel(
            name='BuildingComponentSourceStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_components.buildingcomponent')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study')),
            ],
        ),
        migrations.AddField(
            model_name='buildingcomponent',
            name='source_studies',
            field=models.ManyToManyField(related_name='building_components', through='building_components.BuildingComponentSourceStudy', to='studies.study'),
        ),
        migrations.AddIndex(
            model_name='buildingcomponentsourcestudy',
            index=models.Index(fields=['study'], name='study_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingcomponentsourcestudy',
            unique_together={('building_component', 'study')},
        ),
    ]
