# Generated by Django 5.1.6 on 2025-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0002_columnreinforcementmetadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnreinforcementmetadata',
            name='image',
            field=models.FileField(blank=True, help_text='Image showing the foundation details', null=True, upload_to='foundation_metadata/'),
        ),
    ]
