# Generated by Django 5.1.6 on 2025-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0002_buildingcomponenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingcomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
