# Generated by Django 5.1.6 on 2025-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0003_alter_buildingcomponent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcomponent',
            name='component_bom',
            field=models.JSONField(blank=True, help_text='The bill of materials for the component', null=True),
        ),
    ]
