# Generated by Django 5.1.6 on 2025-03-01 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0003_alter_columnreinforcementmetadata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnreinforcementmetadata',
            name='image',
        ),
        migrations.CreateModel(
            name='ColumnReinforcementMetadataDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, help_text='Image showing the foundation details', null=True, upload_to='documents/')),
                ('column_reinforcement_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='building_components.columnreinforcementmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
