# Generated by Django 5.1.6 on 2025-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0004_buildingcomponent_component_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingcomponent',
            name='type',
            field=models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam')], max_length=255),
        ),
        migrations.AddField(
            model_name='buildingcomponent',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BuildingComponentType',
        ),
    ]
