# Generated by Django 5.1.6 on 2025-03-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0005_columnreinforcementmetadatadocument_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnreinforcementmetadatadocument',
            old_name='document',
            new_name='file',
        ),
    ]
