# Generated by Django 5.1.6 on 2025-04-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0005_alter_buildingcomponent_type_buildingcomponent_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingcomponent',
            name='component_bom',
        ),
    ]
