# Generated by Django 5.1.6 on 2025-03-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0006_rename_document_columnreinforcementmetadatadocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnreinforcementmetadatadocument',
            name='column_reinforcement_metadata',
        ),
        migrations.RemoveField(
            model_name='columnreinforcementmetadatadocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='columnreinforcementmetadatadocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='buildingcomponent',
            name='dimensions',
        ),
        migrations.DeleteModel(
            name='ColumnReinforcementMetadata',
        ),
        migrations.DeleteModel(
            name='ColumnReinforcementMetadataDocument',
        ),
    ]
