# Generated by Django 5.1.6 on 2025-04-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_components', '0006_remove_buildingcomponent_component_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingcomponent',
            name='floor',
        ),
        migrations.AlterField(
            model_name='buildingcomponent',
            name='type',
            field=models.CharField(choices=[('FOOTING', 'Footing'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('SLAB', 'Slab')], max_length=255),
        ),
    ]
