/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_user_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/building-components/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_building_components_list"];
        put?: never;
        post: operations["v1_building_components_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/building-components/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_building_components_retrieve"];
        put: operations["v1_building_components_update"];
        post?: never;
        delete: operations["v1_building_components_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_building_components_partial_update"];
        trace?: never;
    };
    "/api/v1/building-components/bulk-create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new building component. */
        post: operations["v1_building_components_bulk_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/celery-task-result/{task_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_celery_task_result_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        get: operations["v1_draft_building_designs_list"];
        put?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        post: operations["v1_draft_building_designs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        get: operations["v1_draft_building_designs_retrieve"];
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        put: operations["v1_draft_building_designs_update"];
        post?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        delete: operations["v1_draft_building_designs_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        patch: operations["v1_draft_building_designs_partial_update"];
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/building-components/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all building components for a draft building design.
         *     Filter by component type using the 'type' query parameter. */
        get: operations["v1_draft_building_designs_building_components_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/calculation-modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all calculation modules for a draft building design. */
        get: operations["v1_draft_building_designs_calculation_modules_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/column-components/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all column components for a draft building design. */
        get: operations["v1_draft_building_designs_column_components_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/measure-project/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Measure the project of a draft building design. */
        post: operations["v1_draft_building_designs_measure_project_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/upload-design-drawing-details-file/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Handle image files that contain details of the building design. */
        post: operations["v1_draft_building_designs_upload_design_drawing_details_file_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/upload-files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        post: operations["v1_draft_building_designs_upload_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Project model providing CRUD operations. */
        get: operations["v1_projects_list"];
        put?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        post: operations["v1_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Project model providing CRUD operations. */
        get: operations["v1_projects_retrieve"];
        /** @description ViewSet for Project model providing CRUD operations. */
        put: operations["v1_projects_update"];
        post?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        delete: operations["v1_projects_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        patch: operations["v1_projects_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuildingComponent: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            description?: string | null;
            /** @description The data for the component */
            component_data?: unknown;
            type: components["schemas"]["BuildingComponentTypeEnum"];
        };
        /**
         * @description * `FOOTING` - Footing
         *     * `COLUMN` - Column
         *     * `BEAM` - Beam
         *     * `SLAB` - Slab
         * @enum {string}
         */
        BuildingComponentTypeEnum: "FOOTING" | "COLUMN" | "BEAM" | "SLAB";
        DraftBuildingDesign: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            description?: string | null;
            status?: components["schemas"]["DraftBuildingDesignStatusEnum"];
            /** Format: uuid */
            project: string;
            readonly building_components: string[];
        };
        DraftBuildingDesignBuildingComponent: {
            /** Format: uuid */
            readonly uuid: string;
            building_component: components["schemas"]["BuildingComponent"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uuid */
            draft_building_design: string;
        };
        DraftBuildingDesignCalculationModule: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            status?: components["schemas"]["DraftBuildingDesignCalculationModuleStatusEnum"];
            type?: components["schemas"]["DraftBuildingDesignCalculationModuleTypeEnum"];
            /** Format: uuid */
            draft_building_design: string;
        };
        /**
         * @description * `NOT_STARTED` - Not Started
         *     * `IN_PROGRESS` - In Progress
         *     * `COMPLETED` - Completed
         * @enum {string}
         */
        DraftBuildingDesignCalculationModuleStatusEnum: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
        /**
         * @description * `STRUCTURE_PROJECT` - Structure Project
         * @enum {string}
         */
        DraftBuildingDesignCalculationModuleTypeEnum: "STRUCTURE_PROJECT";
        /**
         * @description * `NOT_STARTED` - Not Started
         *     * `CREATING_FOOTING_COMPONENTS` - Creating Footing Components
         *     * `CREATING_COLUMN_COMPONENTS` - Creating Column Components
         *     * `CREATING_BEAM_COMPONENTS` - Creating Beam Components
         *     * `CREATING_SLAB_COMPONENTS` - Creating Slab Components
         *     * `FINISHED` - Finished
         *     * `FAILED` - Failed
         * @enum {string}
         */
        DraftBuildingDesignStatusEnum: "NOT_STARTED" | "CREATING_FOOTING_COMPONENTS" | "CREATING_COLUMN_COMPONENTS" | "CREATING_BEAM_COMPONENTS" | "CREATING_SLAB_COMPONENTS" | "FINISHED" | "FAILED";
        PatchedBuildingComponent: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            description?: string | null;
            /** @description The data for the component */
            component_data?: unknown;
            type?: components["schemas"]["BuildingComponentTypeEnum"];
        };
        PatchedDraftBuildingDesign: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            description?: string | null;
            status?: components["schemas"]["DraftBuildingDesignStatusEnum"];
            /** Format: uuid */
            project?: string;
            readonly building_components?: string[];
        };
        /** @description Serializer for Project model. */
        PatchedProject: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            description?: string;
            reference?: string;
            type?: components["schemas"]["ProjectTypeEnum"];
            readonly created_by?: number;
            readonly updated_by?: number;
        };
        /** @description Serializer for Project model. */
        Project: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            description: string;
            reference: string;
            type?: components["schemas"]["ProjectTypeEnum"];
            readonly created_by: number;
            readonly updated_by: number;
        };
        /**
         * @description * `STRUCTURAL_DESIGN` - Structural Design
         *     * `ARQUITECTURAL_DESIGN` - Arquitectural Design
         * @enum {string}
         */
        ProjectTypeEnum: "STRUCTURAL_DESIGN" | "ARQUITECTURAL_DESIGN";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_building_components_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"][];
                };
            };
        };
    };
    v1_building_components_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingComponent"];
                "application/x-www-form-urlencoded": components["schemas"]["BuildingComponent"];
                "multipart/form-data": components["schemas"]["BuildingComponent"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"];
                };
            };
        };
    };
    v1_building_components_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this building component. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"];
                };
            };
        };
    };
    v1_building_components_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this building component. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingComponent"];
                "application/x-www-form-urlencoded": components["schemas"]["BuildingComponent"];
                "multipart/form-data": components["schemas"]["BuildingComponent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"];
                };
            };
        };
    };
    v1_building_components_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this building component. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_building_components_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this building component. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBuildingComponent"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBuildingComponent"];
                "multipart/form-data": components["schemas"]["PatchedBuildingComponent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"];
                };
            };
        };
    };
    v1_building_components_bulk_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingComponent"];
                "application/x-www-form-urlencoded": components["schemas"]["BuildingComponent"];
                "multipart/form-data": components["schemas"]["BuildingComponent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingComponent"];
                };
            };
        };
    };
    v1_celery_task_result_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_draft_building_designs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"][];
                };
            };
        };
    };
    v1_draft_building_designs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_draft_building_designs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["PatchedDraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_building_components_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesignBuildingComponent"];
                };
            };
        };
    };
    v1_draft_building_designs_calculation_modules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesignCalculationModule"];
                };
            };
        };
    };
    v1_draft_building_designs_column_components_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesignBuildingComponent"];
                };
            };
        };
    };
    v1_draft_building_designs_measure_project_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_upload_design_drawing_details_file_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_upload_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    v1_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
}
