# Generated by Django 5.1.6 on 2025-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enc_key_hash', models.CharField(max_length=255)),
                ('encrypted_value', models.BinaryField(editable=True)),
            ],
        ),
    ]
