/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_user_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/celery-task-result/{task_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_celery_task_result_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        get: operations["v1_draft_building_designs_list"];
        put?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        post: operations["v1_draft_building_designs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        get: operations["v1_draft_building_designs_retrieve"];
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        put: operations["v1_draft_building_designs_update"];
        post?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        delete: operations["v1_draft_building_designs_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        patch: operations["v1_draft_building_designs_partial_update"];
        trace?: never;
    };
    "/api/v1/draft-building-designs/{uuid}/upload-drawing-design/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet for DraftBuildingDesign model providing CRUD operations. */
        post: operations["v1_draft_building_designs_upload_drawing_design_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Project model providing CRUD operations. */
        get: operations["v1_projects_list"];
        put?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        post: operations["v1_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Project model providing CRUD operations. */
        get: operations["v1_projects_retrieve"];
        /** @description ViewSet for Project model providing CRUD operations. */
        put: operations["v1_projects_update"];
        post?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        delete: operations["v1_projects_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for Project model providing CRUD operations. */
        patch: operations["v1_projects_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DraftBuildingDesign: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            description?: string | null;
            phase?: components["schemas"]["PhaseEnum"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: uuid */
            project: string;
            readonly building_components: string[];
        };
        PatchedDraftBuildingDesign: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            description?: string | null;
            phase?: components["schemas"]["PhaseEnum"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: uuid */
            project?: string;
            readonly building_components?: string[];
        };
        /** @description Serializer for Project model. */
        PatchedProject: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            description?: string;
            reference?: string;
            type?: components["schemas"]["TypeEnum"];
            readonly created_by?: number;
            readonly updated_by?: number;
        };
        /**
         * @description * `PHASE_1` - Phase 1
         *     * `PHASE_2` - Phase 2
         *     * `PHASE_3` - Phase 3
         * @enum {string}
         */
        PhaseEnum: "PHASE_1" | "PHASE_2" | "PHASE_3";
        /** @description Serializer for Project model. */
        Project: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            description: string;
            reference: string;
            type?: components["schemas"]["TypeEnum"];
            readonly created_by: number;
            readonly updated_by: number;
        };
        /**
         * @description * `DRAFT` - Draft
         *     * `IN_PROGRESS` - In Progress
         *     * `COMPLETED` - Completed
         * @enum {string}
         */
        StatusEnum: "DRAFT" | "IN_PROGRESS" | "COMPLETED";
        /**
         * @description * `STRUCTURAL_DESIGN` - Structural Design
         *     * `ARQUITECTURAL_DESIGN` - Arquitectural Design
         * @enum {string}
         */
        TypeEnum: "STRUCTURAL_DESIGN" | "ARQUITECTURAL_DESIGN";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_celery_task_result_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_draft_building_designs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"][];
                };
            };
        };
    };
    v1_draft_building_designs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_draft_building_designs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["PatchedDraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_draft_building_designs_upload_drawing_design_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this draft building design. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBuildingDesign"];
                "application/x-www-form-urlencoded": components["schemas"]["DraftBuildingDesign"];
                "multipart/form-data": components["schemas"]["DraftBuildingDesign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftBuildingDesign"];
                };
            };
        };
    };
    v1_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    v1_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    v1_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
}
