# Generated by Django 5.1.6 on 2025-02-23 12:20

import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="BuildingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dimensions",
                    models.JSONField(help_text="The dimensions of the component"),
                ),
                (
                    "component_data",
                    models.JSONField(
                        blank=True, help_text="The data for the component", null=True
                    ),
                ),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        help_text="The embedding vector for the component",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WALL", "Wall"),
                            ("FLOOR", "Floor"),
                            ("CEILING", "Ceiling"),
                            ("ROOF", "Roof"),
                            ("DOOR", "Door"),
                            ("WINDOW", "Window"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[("EXTERIOR", "Exterior"), ("INTERIOR", "Interior")],
                        max_length=255,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("METERS", "Meters"),
                            ("SQUARE_METERS", "Square Meters"),
                            ("CUBIC_METERS", "Cubic Meters"),
                            ("LITERS", "Liters"),
                            ("KILOGRAMS", "Kilograms"),
                            ("UNIT", "Unit"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
