# Generated by Django 5.1.6 on 2025-03-01 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('dimensions', models.JSONField(blank=True, help_text='The dimensions of the material', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='The metadata for the material', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
