# Generated by Django 5.1.6 on 2025-02-24 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('dimensions', models.JSONField(blank=True, help_text='The dimensions of the material', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='The metadata for the material', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
