import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Building } from "lucide-react";
import localFont from "next/font/local";
import { GoogleOAuthProvider } from "@react-oauth/google";
import GoogleOAuthButton from "@/components/auth/google-oauth-button";
const suisse = localFont({
  src: [
    {
      path: "./fonts/suisse/SuisseIntl-Regular-WebM.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/suisse/SuisseIntl-Bold-WebS.woff2",
      weight: "800",
      style: "bold",
    },
    {
      path: "./fonts/suisse/SuisseIntl-Medium-WebM.woff2",
      weight: "500",
      style: "medium",
    },
  ],
  variable: "--font-suisse",
  display: "swap",
});

const nbInternationalPro = localFont({
  src: [
    {
      path: "./fonts/nb-international-pro/nb_international_pro_regular-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/nb-international-pro/nb_international_pro_bold-webfont.woff2",
      weight: "800",
      style: "bold",
    },
    {
      path: "./fonts/nb-international-pro/nb_international_pro_medium-webfont.woff2",
      weight: "500",
      style: "medium",
    },
  ],
  variable: "--font-nb-international-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${suisse.variable} ${nbInternationalPro.className} antialiased`}
      >
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        >
          <div className="pl-[200px] h-full">
            <div
              id="sidebar"
              className="fixed bg-surface-2 top-0 left-0 h-full w-[200px] border-r shadow-md"
            >
              <div className="">
                <GoogleOAuthButton />
                <ul className="py-6">
                  <li className="">
                    <Link
                      href="/"
                      className="flex items-center gap-2 text-md p-4 hover:bg-anchor/20 font-bold "
                    >
                      <Building className="w-5 h-5 mr-2" />
                      Projetos
                    </Link>
                  </li>
                </ul>
              </div>
            </div>

            <div className="h-full">{children}</div>
          </div>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
