# Generated by Django 5.1.6 on 2025-02-23 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_components', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBuildingDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('kind', models.CharField(choices=[('HOUSE', 'House'), ('BUILDING', 'Building')], max_length=255)),
                ('address', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftBuildingDesignBuildingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('justification', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('building_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building_components.buildingcomponent')),
                ('draft_building_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftBuildingDesignBuildingComponentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('draft_building_design_building_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_building_designs.draftbuildingdesignbuildingcomponent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
