# Generated by Django 5.1.6 on 2025-03-05 23:45

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('building_design', models.JSONField(null=True)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
